var UdResult = {
    Success: 0,
    Failure: 1,
    NothingToDo: 2,
    InternalError: 3,
    NotInitialized: 4,
    InvalidConfiguration: 5,
    InvalidParameter: 6,
    OutstandingReferences: 7,
    MemoryAllocationFailure: 8,
    CountExceeded: 9,
    NotFound: 10,
    BufferTooSmall: 11,
    FormatVariationNotSupported: 12,
    ObjectTypeMismatch: 13,
    CorruptData: 14,
    InputExhausted: 15,
    OutputExhausted: 16,
    CompressionError: 17,
    Unsupported: 18,
    Timeout: 19,
    AlignmentRequired: 20,
    DecryptionKeyRequired: 21,
    DecryptionKeyMismatch: 22,
    SignatureMismatch: 23,
    ObjectExpired: 24,
    ParseError: 25,
    InternalCryptoError: 26,
    OutOfOrder: 27,
    OutOfRange: 28,
    CalledMoreThanOnce: 29,
    ImageLoadFailure: 30,
    StreamerNotInitialised: 31,

    OpenFailure: 32,
    CloseFailure: 33,
    ReadFailure: 34,
    WriteFailure: 35,
    SocketError: 36,

    DatabaseError: 37,
    ServerError: 38,
    AuthError: 39,
    NotAllowed: 40,
    InvalidLicense: 41,
    Pending: 42,
    Cancelled: 43,
    OutOfSync: 44,
    SessionExpired: 45,

    ProxyError: 46,
    ProxyAuthRequired: 47,
    ExceededAllowedLimit: 48,

    RateLimited: 49,
    PremiumOnly: 50,
    InProgress: 51,
};
export default Object.freeze(UdResult);